name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v5

      - name: 2. Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://npm.pkg.github.com/
      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: 3. Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: 4. Generate Package
        run: pnpm run compile
        
      - run: pnpm run dist

      - name: 5. Publish Package
        run: pnpm run pub-with-ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
